version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file: common.env
    networks:
      - net

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - net
    depends_on:
      - db
    
networks:
  net:

